# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       alpine

# >> macros
# << macros
%define alpinedir .local/share/%{name}
%define smimedir .local/share/%{name}/smime
%define cachedir .cache/%{name}
%define hack for_spectacle_bug_follows
%if %{sailfishos_version} >= 40400
# SFOS 4.4 ships libxcrypt instead of glibc libcrypt
BuildRequires:  pkgconfig(libcrypt)
BuildRequires:  libxcrypt-compat
%endif

Summary:    Text-based mail and news client. Includes patches by Eduardo Chappa
Version:    2.26
Release:    1
Group:      Applications
License:    ASL 2.0
URL:        http://alpine.x10host.com/alpine/release/
Source0:    http://alpine.x10host.com/alpine/patches/%{name}-%{version}/%{name}-%{version}.tar.xz
Source1:    http://www.alpine.x10host.com/%{name}/patches/%{name}-%{version}/all.patch.gz
Source2:    pine.conf
Source3:    pine.conf.fixed
Source100:  alpine.yaml
Source101:  alpine-rpmlintrc
Patch0:     %SOURCE1
BuildRequires:  pkgconfig(ncurses)
BuildRequires:  pkgconfig(tinfo)
BuildRequires:  pkgconfig(libcrypto)
BuildRequires:  pkgconfig(libssl)
BuildRequires:  pkgconfig(aspell)
BuildRequires:  aspell

%description
A free software email client developed at the University of Washington.

Alpine is a rewrite of the Pine Message System that adds support for
Unicode and other features. It is meant to be suitable for both
inexperienced email users and the most demanding of power users.

"Alpine" officially stands for Alternatively Licensed Program for Internet
News and Email.

%if "%{?vendor}" == "chum"
PackageName: Alpine
DeveloperName: Eduardo Chappa
PackagerName: nephros
Type: console-application
Categories:
  - Office
  - Email
  - News
Screenshots:
  - https://github.com/nephros/sailfish-alpine/raw/master/Screenshot_Alpine_001.png
Custom:
  PackagingRepo: https://github.com/nephros/sailfish-alpine.git
Url:
  Help: http://www.alpine.x10host.com/alpine/alpine-info/
  Bugtracker: http://www.alpine.x10host.com/alpine/contact.html
%endif


%package doc
Summary:    Documentation for %{name}
Group:      Documentation
BuildArch:  noarch

%description doc
%{summary}.

%if "%{?vendor}" == "chum"
DeveloperName: Eduardo Chappa
PackagerName: nephros
Custom:
  PackagingRepo: https://github.com/nephros/sailfish-alpine.git
Categories:
  - Documentation
%endif


%package -n pico
Summary:    The Pico text editor
Group:      Applications

%description -n pico
%{summary}.

Text editor that comes with the Alpine email program.
This is the original that inspired the `nano` text editor.

%if "%{?vendor}" == "chum"
PackageName: Pico
DeveloperName: Eduardo Chappa
PackagerName: nephros
Type: console-application
Categories:
  - Office
  - TextEditor
Custom:
  PackagingRepo: https://github.com/nephros/sailfish-alpine.git
Screenshots:
  - https://github.com/nephros/sailfish-alpine/raw/master/Screenshot_Pico_001.png
Url:
  Help: https://en.wikipedia.org/wiki/Pico_(text_editor)
%endif


%package -n pilot
Summary:    The Pilot file manager
Group:      Applications

%description -n pilot
%{summary}.

File manager program that comes with the Alpine email program.

%if "%{?vendor}" == "chum"
PackageName: Pilot
DeveloperName: Eduardo Chappa
PackagerName: nephros
Type: console-application
Categories:
  - Office
  - FileManager
Screenshots:
  - https://github.com/nephros/sailfish-alpine/raw/master/Screenshot_Pilot_001.png
Custom:
  PackagingRepo: https://github.com/nephros/sailfish-alpine.git
%endif


%package tools
Summary:    Extra binaries for %{name}
Group:      Applications

%description tools
%{summary}.

These are additional tools for the Alpine email program:
rpdump, rpload, mailutil, and dmail

%if "%{?vendor}" == "chum"
PackageName: Alpine tools
DeveloperName: Eduardo Chappa
PackagerName: nephros
Type: console-application
Categories:
  - Email
  - Utility
Custom:
  PackagingRepo: https://github.com/nephros/sailfish-alpine.git
%endif


%prep
%setup -q -n %{name}-%{version}/upstream

# %SOURCE1
%patch0 -p1
# >> setup
printf "INFO: SFOS VERSION is: %s\n" %{sailfishos_version}
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --with-ssl \
    --with-ipv6 \
    --with-pthread \
    --disable-debug \
    --disable-nls \
    --disable-mouse \
    --disable-keyboard-lock \
    --without-ldap \
    --without-krb5 \
    --without-tcl \
    --without-ntlm \
    --with-bundled-tools=mailutil,dmail \
    --enable-from-encoding \
    --with-passfile=%{alpinedir}/.passfile \
    --with-interactive-spellcheck=aspell \
    --with-default-mail-directory=%{alpinedir}/mail \
    --with-default-addressbook=%{alpinedir}/addressbook \
    --with-default-signature-file=%{alpinedir}/signature \
    --with-smime-public-cert-directory=%{smimedir}/public \
    --with-smime-private-key-directory=%{smimedir}/private \
    --with-smime-cacert-directory=%{smimedir}/ca \
    --with-default-html-directory=%{cachedir}/html \
    --with-local-support-info="%{_datadir}"/%{name}/pine.info \
    --with-system-pinerc="%{_datadir}"/%{name}/pine.conf \
    --with-system-fixed-pinerc="%{_datadir}"/%{name}/pine.conf.fixed \
    --with-encryption-minimum-version=tls1_1

make %{?_smp_mflags}

# >> build post
pushd imap
pushd mailutil
make %{?_smp_mflags}
popd
pushd dmail
make %{?_smp_mflags}
popd
popd
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
pushd imap
#make DESTDIR=%%{buildroot} bindir=%%{_bindir} mandir=%%{_mandir} install-mailutil
install -s -D -m 0755 mailutil/mailutil %{buildroot}%{_bindir}/mailutil
install -s -D -m 0755 dmail/dmail %{buildroot}%{_bindir}/dmail
popd
install -D -m 644 %SOURCE2 %{buildroot}%{_datadir}/%{name}/pine.conf
install -D -m 644 %SOURCE3 %{buildroot}%{_datadir}/%{name}/pine.conf.fixed

# we don't need those in the package:
rm -f doc/tech-notes/Makefile
rm -f doc/tech-notes/pn4tn
rm -f doc/tech-notes/pnuts.4tech-notes
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%config %{_datadir}/%{name}/pine.conf
%config %{_datadir}/%{name}/pine.conf.fixed
%ghost %config %{_sysconfdir}/c-client.conf
# >> files
# << files

%files doc
%defattr(-,root,root,-)
%doc README NOTICE
%doc doc/brochure.txt
%doc doc/tech-notes/*
%doc doc/mailcap.unx
%doc doc/mime.types
%{_mandir}/man1/*
# >> files doc
# << files doc

%files -n pico
%defattr(-,root,root,-)
%{_bindir}/pico
# >> files pico
# << files pico

%files -n pilot
%defattr(-,root,root,-)
%{_bindir}/pilot
# >> files pilot
# << files pilot

%files tools
%defattr(-,root,root,-)
%{_bindir}/rpdump
%{_bindir}/rpload
%{_bindir}/mailutil
%{_bindir}/dmail
# >> files tools
# << files tools
