# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       alpine

# >> macros
# << macros

Summary:    Text-based mail and news client. Includes patches by Eduardo Chappa
Version:    2.25
Release:    3
Group:      Applications
License:    ASL 2.0
URL:        http://alpine.x10host.com/alpine/release/
Source0:    http://alpine.x10host.com/alpine/patches/%{name}-%{version}/%{name}-%{version}.tar.xz
Source1:    http://www.alpine.x10host.com/%{name}/patches/%{name}-%{version}/all.patch.gz
Source2:    pine.conf
Source3:    pine.conf.fixed
Source100:  alpine.yaml
Patch0:     %{name}-%{version}-%SOURCE1
BuildRequires:  pkgconfig(ncurses)
BuildRequires:  pkgconfig(tinfo)
BuildRequires:  pkgconfig(libcrypto)
BuildRequires:  pkgconfig(libssl)

%description
A free software email client developed at the University of Washington.

Alpine is a rewrite of the Pine Message System that adds support for
Unicode and other features. It is meant to be suitable for both
inexperienced email users and the most demanding of power users.

"Alpine" officially stands for Alternatively Licensed Program for Internet
News and Email.


%package doc
Summary:    Documentation for %{name}
Group:      Documentation
BuildArch:  noarch

%description doc
%{summary}.

%package -n pico
Summary:    The pico text editor
Group:      Applications

%description -n pico
%{summary}.

%package -n pilot
Summary:    The pilot file manager
Group:      Applications

%description -n pilot
%{summary}.

%package tools
Summary:    Extra binaries for %{name}
Group:      Applications

%description tools
%{summary}.

%prep
%setup -q -n %{name}-%{version}/upstream

# %{name}-%{version}-%SOURCE1
%patch0 -p1
# >> setup
#%%setup -q -n %{name}-%{version}/upstream
#%%apply_patch %{name}-%{version}-%%SOURCE1


# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --with-ssl \
    --with-ipv6 \
    --with-pthread \
    --disable-debug \
    --disable-nls \
    --disable-mouse \
    --disable-keyboard-lock \
    --without-ldap \
    --without-krb5 \
    --without-tcl \
    --without-ntlm \
    --with-bundled-tools=mailutil,dmail \
    --with-passfile=.alpine-passfile \
    --enable-from-encoding \
    --with-interactive-spellcheck=/usr/bin/aspell \
    --with-local-support-info="%{_datadir}"/%{name}/pine.info \
    --with-system-pinerc="%{_datadir}"/%{name}/pine.conf \
    --with-system-fixed-pinerc="%{_datadir}"/%{name}/pine.conf.fixed \
    --with-encryption-minimum-version=tls1_1 \
    --with-ssl-certs-dir=/etc/ssl/certs

make %{?_smp_mflags}

# >> build post
pushd imap
pushd mailutil
make %{?_smp_mflags}
popd
pushd dmail
make %{?_smp_mflags}
popd
popd
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
pushd imap
#make DESTDIR=%%{buildroot} bindir=%%{_bindir} mandir=%%{_mandir} install-mailutil
install -s -D -m 0755 mailutil/mailutil %{buildroot}%{_bindir}/mailutil
install -s -D -m 0755 dmail/dmail %{buildroot}%{_bindir}/dmail
popd
install -D -m 644 %SOURCE1 %{buildroot}%{_datadir}/%{name}/pine.conf
install -D -m 644 %SOURCE2 %{buildroot}%{_datadir}/%{name}/pine.conf.fixed

# we don't need those in the package:
rm -f doc/tech-notes/Makefile
rm -f doc/tech-notes/pn4tn
rm -f doc/tech-notes/pnuts.4tech-notes
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%config %{_datadir}/%{name}/pine.conf
%config %{_datadir}/%{name}/pine.conf.fixed
%ghost %config %{_sysconfdir}/c-client.conf
# >> files
# << files

%files doc
%defattr(-,root,root,-)
%doc README NOTICE
%doc doc/brochure.txt
%doc doc/tech-notes/*
%doc doc/mailcap.unx
%doc doc/mime.types
%{_mandir}/man1/*
# >> files doc
# << files doc

%files -n pico
%defattr(-,root,root,-)
%{_bindir}/pico
# >> files pico
# << files pico

%files -n pilot
%defattr(-,root,root,-)
%{_bindir}/pilot
# >> files pilot
# << files pilot

%files tools
%defattr(-,root,root,-)
%{_bindir}/rpdump
%{_bindir}/rpload
%{_bindir}/mailutil
%{_bindir}/dmail
# >> files tools
# << files tools
